### ISSUE TITLE
Customize the label names for each category

### ISSUE THREAD

**Issue by kristw** [hamelsmu/MLapp#25]
For example, my repo use label `#bug` instead of `bug`, and `#enhancement` instead of `feature_request`. It would be great if I can tell the bot to label with the terms I use.

**Comment by hamelsmu** [comment]
Thanks @kristw how would you feel about this being implemented via a config file of some kind in your repo?  Like yaml ex: -bug: #bug

**Comment by kristw** [comment]
That would work well. Most of the bot let user create config file under `.github` dir.

**Comment by hamelsmu** [comment]
@kristw I think I fixed this is issue, I made PRs on those repos.  If you like the app please spread the love ❤️  thank you

**Comment by kristw** [comment]
Awesome. Thank you so much!

**Comment by kristw** [comment]
Verify by creating dummy issue
https://github.com/apache-superset/superset-ui-plugins/issues/63
Seems to work correctly so I am closing this issue now. 
Thank you so much for your swift response.
